version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"  # Corrected format: use a space after the hyphen
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

